# Generated by Django 3.2.16 on 2023-01-30 12:59

from django.db import migrations, models
import ivh_inventario.core.utils.gerador_codigo


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cod_redefinicao',
            field=models.CharField(default=ivh_inventario.core.utils.gerador_codigo.geracao_codigo, max_length=10, verbose_name='Código de redefinição de senha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
