# Generated by Django 3.2.16 on 2023-03-23 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20230130_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo_notificacao', models.CharField(choices=[('ADMINS', 'Administradores'), ('USUARIOS', 'Usuários'), ('TODOS', 'Todos'), ('PRIVADA', 'Privada')], default='USUARIOS', max_length=50, verbose_name='Tipo de notificação')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
