# Generated by Django 3.2.16 on 2023-04-08 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0005_rename_identificador_doador_cnpj_cpf'),
        ('entrada', '0002_alter_entrada_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='doador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doador.doador'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='doc_fisc',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Documento fiscal'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='is_doacao',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='tipo_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='val_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='val_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
