# Generated by Django 3.2.18 on 2023-04-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0003_auto_20230408_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='entrada_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrada.entrada'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='is_ultimo',
            field=models.BooleanField(default=True),
        ),
    ]
