# Generated by Django 3.2.18 on 2023-04-25 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0004_auto_20230422_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='dt_entrada',
            field=models.DateField(default=datetime.date(2023, 4, 25), verbose_name='Data de entrada'),
        ),
    ]
