# Generated by Django 3.2.18 on 2023-04-25 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0005_alter_entrada_dt_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='quantidade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade'),
        ),
    ]
