# Generated by Django 3.2.16 on 2023-04-26 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0007_alter_entrada_dt_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='dt_entrada',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 26), null=True, verbose_name='Data de entrada'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='is_doacao',
            field=models.BooleanField(default=True),
        ),
    ]
