# Generated by Django 3.2.16 on 2023-01-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
