# Generated by Django 3.2.16 on 2023-01-26 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_alter_item_tipo_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('estoque_atual', models.IntegerField(default=1, verbose_name='Estoque atual')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
    ]
