# Generated by Django 3.2.16 on 2023-01-25 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_bem_de_consumo', models.BooleanField()),
                ('grupo', models.CharField(choices=[('equipamento', 'equipamento'), ('gêneros alimentícios', 'gêneros alimentícios'), ('higiene pessoal', 'higiene pessoal'), ('limpeza', 'limpeza'), ('medicamento', 'medicamento'), ('não identificado', 'não identificado')], max_length=200)),
                ('cod', models.CharField(blank=True, max_length=50, null=True)),
                ('doc_fisc', models.CharField(blank=True, max_length=50, null=True)),
                ('is_doacao', models.BooleanField()),
                ('validade', models.DateField(blank=True, null=True)),
                ('val_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('val_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.TextField()),
                ('tipo_unit', models.CharField(max_length=10)),
            ],
        ),
    ]
