# Generated by Django 3.2.16 on 2023-03-10 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0004_alter_doador_identificador'),
        ('item', '0003_alter_item_doc_fisc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='doador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doador.doador'),
        ),
    ]
