# Generated by Django 3.2.16 on 2023-04-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_doador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='doador',
        ),
        migrations.RemoveField(
            model_name='item',
            name='doc_fisc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_doacao',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tipo_unit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='val_total',
        ),
        migrations.RemoveField(
            model_name='item',
            name='val_unit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='validade',
        ),
    ]
