# Generated by Django 3.2.18 on 2023-04-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_estoque_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estoque_atual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
