# Generated by Django 3.2.18 on 2023-04-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_item_estoque_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cod',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='estoque_atual',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
