
export const Routes = {
    // pages
    Presentation: { path: "/a" },
    DashboardOverview: { path: "/dashboard" },
    ListUsuario: { path: "/usuarios/list" },
    CreateUsuario: { path: "/usuarios/create" },
    EditUsuario: { path: "/usuarios/edit" },
    DeleteUsuario: { path: "/usuarios/delete" },
    ListEstoqueAtual: { path: "/estoque-atual" },
    EditEstoque: { path: "/estoque-atual/edit" },
    CreateEntrada: { path: "/entrada/create" },
    ListEntrada: { path: "/entrada/list" },
    EditEntrada: { path: "/entrada/edit" },
    CreateSaida: { path: "/saida/create" },
    ListSaida: { path: "/saida/list" },
    EditSaida: { path: "/saida/edit" },
    Upgrade: { path: "/upgrade" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    Billing: { path: "/examples/billing" },
    Invoice: { path: "/examples/invoice" },
    Signin: { path: "/" },
    Signup: { path: "/registro" },
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/examples/404" },
    ServerError: { path: "/examples/500" },

    // docs
    DocsOverview: { path: "/documentation/overview" },
    DocsDownload: { path: "/documentation/download" },
    DocsQuickStart: { path: "/documentation/quick-start" },
    DocsLicense: { path: "/documentation/license" },
    DocsFolderStructure: { path: "/documentation/folder-structure" },
    DocsBuild: { path: "/documentation/build-tools" },
    DocsChangelog: { path: "/documentation/changelog" },

    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" }
};