# Generated by Django 3.2.16 on 2023-02-15 20:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('nome', models.CharField(max_length=200, verbose_name='nome/fornecedor')),
                ('identificador', models.CharField(max_length=200, verbose_name='cpf/cnpj')),
            ],
        ),
    ]
