# Generated by Django 3.2.16 on 2023-02-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doador',
            old_name='identificador',
            new_name='cpf_cnpj',
        ),
    ]
