# Generated by Django 3.2.16 on 2023-03-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0002_rename_identificador_doador_cpf_cnpj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doador',
            old_name='cpf_cnpj',
            new_name='identificador',
        ),
    ]
