# Generated by Django 3.2.16 on 2023-04-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0004_alter_doador_identificador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doador',
            old_name='identificador',
            new_name='cnpj_cpf',
        ),
    ]
