# Generated by Django 3.2.16 on 2023-04-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saida',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saida',
            name='erro_saida',
            field=models.BooleanField(default=False),
        ),
    ]
