# Generated by Django 3.2.18 on 2023-04-22 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saida', '0002_auto_20230408_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='saida',
            name='is_ultimo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saida',
            name='saida_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saida.saida'),
        ),
    ]
