# Generated by Django 3.2.18 on 2023-04-25 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saida', '0003_auto_20230422_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida',
            name='dt_saida',
            field=models.DateField(default=datetime.date(2023, 4, 25)),
        ),
    ]
