# Generated by Django 3.2.18 on 2023-04-25 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saida', '0004_alter_saida_dt_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida',
            name='quantidade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade'),
        ),
    ]
