# Generated by Django 3.2.16 on 2023-04-26 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saida', '0006_alter_saida_dt_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida',
            name='dt_saida',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 26), null=True),
        ),
    ]
